version: "2"
services:
  db:
    image: postgres:9.4.0
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/foosball-api
    links:
      - db:postgres
    ports:
      - "10030:3000"
